# Generated by Django 5.0.1 on 2024-01-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='AircraftCode',
            field=models.ForeignKey(db_column='AircraftCode', on_delete=django.db.models.deletion.DO_NOTHING, to='pilotlog.aircraft', to_field='AircraftCode'),
        ),
    ]
