# Generated by Django 5.0.1 on 2024-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_Modified', models.IntegerField()),
                ('QCode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('RefExtra', models.IntegerField(blank=True, null=True)),
                ('RefModel', models.CharField(blank=True, max_length=50, null=True)),
                ('Validity', models.IntegerField(blank=True, null=True)),
                ('DateValid', models.DateField(blank=True, null=True)),
                ('QTypeCode', models.IntegerField(blank=True, null=True)),
                ('DateIssued', models.DateField(blank=True, null=True)),
                ('MinimumQty', models.IntegerField(blank=True, null=True)),
                ('NotifyDays', models.IntegerField(blank=True, null=True)),
                ('RefAirfield', models.CharField(blank=True, max_length=100, null=True)),
                ('MinimumPeriod', models.IntegerField(blank=True, null=True)),
                ('NotifyComment', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Qualification',
            },
        ),
    ]
