# Generated by Django 5.0.1 on 2024-01-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0002_alter_flight_aircraftcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='AircraftCode',
            new_name='Aircraft',
        ),
    ]
