# Generated by Django 5.0.1 on 2024-03-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0005_remove_myquerybuild_mqcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquerybuild',
            name='mQ',
            field=models.ForeignKey(db_column='mQCode', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pilotlog.myquery', to_field='mQCode'),
            preserve_default=False,
        ),
    ]
